version: '3'
services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul-server
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -bind=0.0.0.0 -advertise=127.0.0.1
    ports:
      - "8500:8500"
    network_mode: "host"
    volumes:
      - consul-data:/consul/data
volumes:
  consul-data: 