# Gateway Service Configuration
gateway:
  host: "0.0.0.0"
  port: 50051

# Node Service Configuration
node:
  id: "node3"
  port: 50056
  health_check:
    path: "/health"
    port: 50057
    interval: "10s"
    timeout: "5s"
  chains:
    - "ethereum"
    - "polygon"

# Consul Configuration
consul:
  host: "localhost"
  port: 8500

# Logging Configuration
log:
  level: "info"
  format: "text"